In [1]:
import numpy as np

In [4]:
list = [1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
numpyList = np.array(list)
print(numpyList)
numpyList.dtype

[ 1  2  3  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


dtype('int64')

In [5]:
numpyList = numpyList.astype(float)
print(numpyList)
numpyList.dtype

[ 1.  2.  3.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19.
 20.]


dtype('float64')

In [6]:
data = {i : np.random.randn() for i in range(7)}
data

{0: -0.9984881639241538,
 1: -1.213281422201764,
 2: -0.37407702046902547,
 3: 0.6197701618012973,
 4: -0.9913532734080279,
 5: -0.46509090956260457,
 6: -1.5662724404743635}

In [12]:
array = np.array([1,2,3,4,5])
print("array, ", array)
asarray = np.asarray([1,2,3,4,5])
print("asarray, ", asarray)
arange = np.arange(1,10,2)
print("arange, ", arange)
ones = np.ones((3,3))
print("ones, \n", ones)
zeros = np.zeros((3,3))
print("zeros, \n", zeros)
empty = np.empty((3,3))
print("empty, \n", empty)
eye = np.eye(3, dtype=np.int32)
print("eye, \n", eye)
identity = np.identity(3)
print("identity, \n", identity)
full = np.full((4,4), 9)
print("full, \n", full)
ones_like = np.ones_like(full)
print("ones_like, \n", ones_like)


array,  [1 2 3 4 5]
asarray,  [1 2 3 4 5]
arange,  [1 3 5 7 9]
ones, 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
zeros, 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
empty, 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
eye, 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
identity, 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
full, 
 [[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
ones_like, 
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [14]:
complex64 = np.array([1+2j, 3+4j, 5+6*1j])
print("complex64, ", complex64)

unicode_ = np.array([1,2,3,'adf','asd'], dtype=np.unicode_)
print("unicode_, ", unicode_)

string_ = np.array([1,2,3,'q','asd'], dtype=np.string_)
print("string_, ", string_)
string_.shape

complex64,  [1.+2.j 3.+4.j 5.+6.j]
unicode_,  ['1' '2' '3' 'adf' 'asd']
string_,  [b'1' b'2' b'3' b'q' b'asd']


(5,)