In [24]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [25]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 5.34 ms, sys: 4.29 ms, total: 9.64 ms
Wall time: 7.14 ms


In [27]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 275 ms, sys: 58.5 ms, total: 334 ms
Wall time: 334 ms


In [5]:
data = np.random.randn(2, 3)
data


array([[-0.97362528,  0.66031114,  0.07222963],
       [ 0.75038376,  1.07936868, -0.52376999]])

In [6]:
data*10


array([[-9.73625276,  6.60311137,  0.72229634],
       [ 7.50383761, 10.79368682, -5.23769991]])

In [7]:
data+data

array([[-1.94725055,  1.32062227,  0.14445927],
       [ 1.50076752,  2.15873736, -1.04753998]])

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

In [18]:
data1=[6, 5, 7.5]
arr1 = np.array(data1)
arr1

array([6. , 5. , 7.5])

In [19]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr2.ndim

2

In [21]:
arr2.shape

(2, 4)

In [22]:
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int64')

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [29]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [30]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype


dtype('float64')

In [35]:
arr2.dtype

dtype('int32')

In [37]:
arr = np.array([1, 2, 3, 4, 5])

In [38]:
arr.dtype

dtype('int64')

In [39]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [42]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [43]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [53]:
numeric_strings = np.array(['1.25', '–9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 0: ordinal not in range(128)

In [54]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [67]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [68]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [69]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [70]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [71]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [73]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [74]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [75]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [77]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
arr[5]

5

In [79]:
arr[5:8]

array([5, 6, 7])

In [83]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [85]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [86]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [87]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [90]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [91]:
arr2d[2]

array([7, 8, 9])

In [92]:
arr2d[0][2]

3

In [93]:
arr2d[0, 2]

3

In [94]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [95]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [98]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [99]:
arr3d[1, 0]

array([7, 8, 9])

In [101]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])