In [120]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))


In [121]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 15.2 ms


In [122]:
 %time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 975 ms


In [123]:
 arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [124]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [125]:
arr * arr


array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [126]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [127]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [128]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [129]:
 arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [130]:
arr2


array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [131]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [132]:
arr = np.arange(10)

In [133]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
arr[5]

5

In [135]:
 arr[5:8]


array([5, 6, 7])

In [136]:
 arr[5:8] = 12

In [137]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [138]:
arr_slice = arr[5:8]

In [139]:
arr_slice

array([12, 12, 12])

In [140]:
 arr_slice[1] = 12345

In [141]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [142]:
arr_slice[:] = 64

In [143]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [144]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [145]:
arr2d[2]

array([7, 8, 9])

In [146]:
arr2d[0][2]

3

In [147]:
 arr2d[0, 2]

3

In [148]:
 arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [149]:
 arr3d 

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [150]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [151]:
 old_values = arr3d[0].copy()


In [152]:
arr3d[0] = 42

In [153]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [154]:
arr3d[0] = old_values

In [155]:
arr3d[1, 0]

array([7, 8, 9])

In [156]:
x = arr3d[1]

In [157]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [158]:
x[0]

array([7, 8, 9])

In [159]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [160]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [161]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [162]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [163]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [164]:
arr2d[1, :2]

array([4, 5])

In [165]:
arr2d[:2, 2]

array([3, 6])

In [166]:
arr2d[:, :1]


array([[1],
       [4],
       [7]])

In [167]:
arr2d[:2, 1:] = 0

In [168]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [169]:
 names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [170]:
data = np.random.randn(7, 4)

In [171]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [172]:
data

array([[ 0.64920163,  0.68065125,  0.33370412,  0.95414421],
       [-0.8352252 ,  0.4925601 ,  1.59883281, -0.390885  ],
       [-0.43211395,  0.87759835, -0.83062576,  0.10785046],
       [ 1.53940325, -0.53016247, -0.81074976, -0.02223439],
       [-0.59661721, -1.21850653, -0.12653854,  0.50253359],
       [-0.54691469, -0.43875805,  0.15049355, -1.81903267],
       [ 1.14075273,  1.14966051, -0.55609055, -1.18056969]])

In [173]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [174]:
data[names == 'Bob']

array([[ 0.64920163,  0.68065125,  0.33370412,  0.95414421],
       [ 1.53940325, -0.53016247, -0.81074976, -0.02223439]])

In [175]:
data[names == 'Bob', 2:]

array([[ 0.33370412,  0.95414421],
       [-0.81074976, -0.02223439]])

In [176]:
 data[names == 'Bob', 3]

array([ 0.95414421, -0.02223439])

In [177]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [178]:
data[~(names == 'Bob')]

array([[-0.8352252 ,  0.4925601 ,  1.59883281, -0.390885  ],
       [-0.43211395,  0.87759835, -0.83062576,  0.10785046],
       [-0.59661721, -1.21850653, -0.12653854,  0.50253359],
       [-0.54691469, -0.43875805,  0.15049355, -1.81903267],
       [ 1.14075273,  1.14966051, -0.55609055, -1.18056969]])

In [179]:
cond = names == 'Bob'

In [180]:
 data[~cond]

array([[-0.8352252 ,  0.4925601 ,  1.59883281, -0.390885  ],
       [-0.43211395,  0.87759835, -0.83062576,  0.10785046],
       [-0.59661721, -1.21850653, -0.12653854,  0.50253359],
       [-0.54691469, -0.43875805,  0.15049355, -1.81903267],
       [ 1.14075273,  1.14966051, -0.55609055, -1.18056969]])

In [181]:
mask = (names == 'Bob') | (names == 'Will')

In [182]:
mask

array([ True, False,  True,  True,  True, False, False])

In [183]:
 data[mask]

array([[ 0.64920163,  0.68065125,  0.33370412,  0.95414421],
       [-0.43211395,  0.87759835, -0.83062576,  0.10785046],
       [ 1.53940325, -0.53016247, -0.81074976, -0.02223439],
       [-0.59661721, -1.21850653, -0.12653854,  0.50253359]])

In [184]:
data[data < 0] = 0

In [185]:
data

array([[0.64920163, 0.68065125, 0.33370412, 0.95414421],
       [0.        , 0.4925601 , 1.59883281, 0.        ],
       [0.        , 0.87759835, 0.        , 0.10785046],
       [1.53940325, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.50253359],
       [0.        , 0.        , 0.15049355, 0.        ],
       [1.14075273, 1.14966051, 0.        , 0.        ]])

In [186]:
 data[names != 'Joe'] = 7


In [187]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.4925601 , 1.59883281, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.15049355, 0.        ],
       [1.14075273, 1.14966051, 0.        , 0.        ]])

In [188]:
arr = np.empty((8, 4))

In [189]:
 for i in range(8):arr[i] = i

In [190]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [191]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [192]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [193]:
 arr = np.arange(32).reshape((8, 4))
    

In [194]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [195]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]


array([ 4, 23, 29, 10])

In [196]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [197]:
arr = np.arange(15).reshape((3, 5))

In [198]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [199]:
 arr = np.random.randn(6, 3)

In [200]:
arr

array([[ 0.28993537,  0.41867499,  0.01069482],
       [ 0.45298186,  0.43479013,  1.14466399],
       [ 0.63846042, -0.97350752,  1.78708928],
       [-1.17918525, -1.16678142, -1.3472962 ],
       [ 0.62702948,  0.21667205, -0.36724386],
       [ 0.48104712,  0.24282602,  0.46259487]])

In [201]:
np.dot(arr.T, arr)

array([[2.71193694, 1.32531666, 3.24356761],
       [1.32531666, 2.77933822, 0.36718016],
       [3.24356761, 0.36718016, 6.66812728]])

In [202]:
arr = np.arange(16).reshape((2, 2, 4))

In [203]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [204]:
 arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [205]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [206]:
 arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])